### ISSUE TITLE
Status of miniee

### ISSUE THREAD

**Issue by svizzari** [mixu/miniee#2]
Hey @mixu :smile_cat: 

Just curious, do you still use Miniee yourself?  If not, what are you using instead?  Do you have any plans to release any updates or is pretty much feature complete and still relevant?

Cheers

**Comment by mixu** [comment]
@svizzari I've switched over to [microee](https://github.com/mixu/microee), which is the same thing but shorter. I consider both projects to be pretty much feature complete since eventemitters are fairly simple. More recently I've started working with pipes and streams a lot more, see https://github.com/mixu/pipe-iterators and https://github.com/mixu/ghost-render/blob/master/lib/pipelines.js#L44 / https://github.com/mixu/markdown-styles/blob/master/lib/pipeline.js for some examples.

**Comment by svizzari** [comment]
Cool, thanks for the reply @mixu 

I'm going to use Microee for now (in the browser) and spend some more time looking at Streams and Pipes in a node context.  Coincidentally, what is your opinion on io.js?

**Comment by mixu** [comment]
Good to hear that. io.js is pretty compelling right now because V8 from six months ago (= node 0.12) vs a more recent V8 (= io.js) makes quite a big difference in terms of the ES6 features that are natively supported. I think once ES6 is mostly shipped there will be fewer differences between the two, but overall it's a big positive to get access to those features quickly.
